# Generated by Django 2.2.2 on 2020-09-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.CharField(
                blank=True,
                help_text='手机号',
                max_length=16,
                null=True,
                unique=True,
                verbose_name='手机号',
            ),
        ),
    ]
