# Generated by Django 2.2.2 on 2020-09-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'fid',
                    models.AutoField(
                        help_text='Friend ID',
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(help_text='姓名', max_length=16, verbose_name='姓名'),
                ),
                (
                    'gender',
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(0, '女'), (1, '男'), (2, '保密')],
                        help_text='性别',
                        verbose_name='性别',
                    ),
                ),
                (
                    'age',
                    models.IntegerField(blank=True, help_text='年龄', verbose_name='年龄'),
                ),
            ],
            options={'verbose_name': '朋友', 'verbose_name_plural': '朋友',},
        ),
    ]
